name: PLT CI build and test

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'

  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]
  
jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup environment
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install build-essential \
        dia \
        libsfml-dev libxml2-dev libmicrohttpd-dev libboost-all-dev \
        python3 python3-pip \
        lcov gcovr \
        /

    - name: Build
      shell: bash
      run: |
        make all

    - name: Test
      working-directory: ${{runner.workspace}}/build/test
      shell: bash
      run: |
        chmod a+x build/run_test.sh
        build/run_test.sh
      
